version: '3.6'
services:

  webapp:
    image: todhm/flask_spark_webapp
    working_dir: /app
    command: gunicorn -b 0.0.0.0:8000 --reload -w 4  wsgi:app
    networks:
        - sparknetwork
    deploy:
      placement:
        constraints: [node.hostname == default]
    ports:
      - "8000:8000"
    depends_on:
      - spark-master
      - redis
      - mongo
    environment:
     - SPARK_APPLICATION_PYTHON_LOCATION =/app/wsgi.py
     - SPARK_MASTER_NAME=spark-master
     - SPARK_MASTER_PORT=7077
     - PYSPARK_PYTHON=python3
     - APP_SETTINGS=settings.ProductionConfig

  celery_worker:
    image: todhm/flask_spark_webapp
    working_dir: /app
    command: celery -A celery_worker:celery worker  --loglevel=INFO
    networks:
        - sparknetwork
    ports:
      - "9000:9000"

    deploy:
      placement:
        constraints: [node.hostname == default]

    depends_on:
      - webapp
      - spark-master
      - redis
    environment:
     - "SPARK_MASTER=spark://spark-master:7077"
     - SPARK_APPLICATION_PYTHON_LOCATION =/app/wsgi.py
     - SPARK_MASTER_NAME=spark-master
     - SPARK_MASTER_PORT=7077
     - PYSPARK_PYTHON=python3
     - APP_SETTINGS=settings.ProductionConfig


  celery_beat:
    image: todhm/flask_spark_webapp
    working_dir: /app
    command: celery -A celery_worker:celery beat  --loglevel=INFO
    networks:
        - sparknetwork
    ports:
      - "9050:9050"
    depends_on:
      - webapp
      - spark-master
      - redis
      - celery_worker
    environment:
     - "SPARK_MASTER=spark://spark-master:7077"
     - SPARK_APPLICATION_PYTHON_LOCATION =/app/wsgi.py
     - SPARK_MASTER_NAME=spark-master
     - SPARK_MASTER_PORT=7077
     - PYSPARK_PYTHON=python3
     - APP_SETTINGS=settings.ProductionConfig

  mongo:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-1:/data/db
      - ./mongo/shoppings:/shoppings
      - mongo-config-1:/data/configdb
    networks:
      - sparknetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 1
          - node.hostname == default

  mongo2:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-2:/data/db
      - mongo-config-2:/data/configdb
    networks:
      - sparknetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 2

  mongo3:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-3:/data/db
      - mongo-config-3:/data/configdb
    networks:
      - sparknetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 3

  redis:
    image: redis:alpine
    networks:
        - sparknetwork


  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    networks:
    - sparknetwork
    ports:
      - "8080:8080"
      - "7077:7077"
    deploy:
      placement:
        constraints: [node.hostname == default]

    environment:
      - INIT_DAEMON_STEP=setup_spark


  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    networks:
    - sparknetwork

    deploy:
      placement:
        constraints: [node.hostname == default]
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"


  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    networks:
    - sparknetwork
    depends_on:
      - spark-master
    deploy:
        replicas: 10
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"


volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  mongo-config-1:
  mongo-config-2:
  mongo-config-3:

networks:
    sparknetwork:
